In [1]:
import numpy as np

In [2]:
x = np.array([100,400,-50,-40])#each ele a
y = np.array([10,15,20,25])#each ele b
condition = np.array([True,True,False, False])#each ele cond

print(x)
print(y)
print(condition)

[100 400 -50 -40]
[10 15 20 25]
[ True  True False False]


In [3]:
#create an array based on condition, if it's true then value of x else y

In [4]:
z = [a if cond else b for a,cond,b in zip(x,condition,y)]
print(z)

[100, 400, 20, 25]


In [5]:
#cons of these statement-> confusing, long statement

In [6]:
#use np.where istead
#np.where(condition,values for true,values for false)

In [7]:
z2 = np.where(condition,x,y)
print(z2)

[100 400  20  25]


In [12]:
z3 = np.where(x>0,x,0)
print(z3)

[100 400   0   0]


In [13]:
#np.sum()

In [14]:
print(x.sum())

410


In [17]:
x2 = np.array([[1,2],[3,4]])
print(x2)

[[1 2]
 [3 4]]


In [21]:
print(x2.sum())
print(x2.sum(0))
print(x2.sum(1))

10
[4 6]
[3 7]


In [22]:
#logical AND, OR operation - any(), all()

In [23]:
condition2 = np.array([True,False,True])

#OR
print(condition.any())

#and
print(condition.all())

True
False


In [27]:
unsorted = np.array([5,4,3,2,1])
print(unsorted)
sort_arr = unsorted.sort()
print(unsorted)

[5 4 3 2 1]
[1 2 3 4 5]


In [36]:
#np.unique()

In [37]:
arr2 = np.array([1,2,4,1,5,2,56,12,12,2])
print(arr2)
print(np.unique(arr2))

[ 1  2  4  1  5  2 56 12 12  2]
[ 1  2  4  5 12 56]


In [38]:
#in1d()
#to check whether the list is present in the array or not

In [39]:
print(np.in1d([2,3,4,0],arr2))

[ True False  True False]
