In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#why do we need to save arrays to hard drive?

In [8]:
#saving single array

np.save('saved_array',arr)

In [9]:
#load single array

load_arr1 = np.load('saved_array.npy')
print(load_arr1)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
#saving multiple array

arr2 = np.arange(25)
arr3 = np.arange(5)

np.savez('Multiple_array.npz',x=arr2, y=arr3)

In [14]:
#loading multiple file
load_npz = np.load('Multiple_array.npz')
print(load_npz['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [15]:
#saving array in text format

np.savetxt('myarray.txt',arr2,delimiter=',')

In [17]:
#loading array in txt fromat

load_txt = np.loadtxt('myarray.txt',delimiter=',')
print(load_txt)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [ ]:
#delimeter is used to seperate values of array