In [1]:
import numpy as np

In [12]:
arr = np.arange(100,150,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]


In [4]:
#access using indexes

print(arr[0])
print(arr[1])
print(arr[3])

100
102
106


In [7]:
#slicing of array index arr(start:stop:step)

print(arr[0:5:1])
print(arr[::-1])

[100 102 104 106 108]
[148 146 144 142 140 138 136 134 132 130 128 126 124 122 120 118 116 114
 112 110 108 106 104 102 100]


In [14]:
#update the array using slices

print(arr)
arr[0:5] = 0
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]
[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]


In [16]:
#interesting about array - memory allocation - view vs copy

arr2 = arr[4:10]
print(arr2)
arr2[:] = 1
print(arr2)

[  0 110 112 114 116 118]
[1 1 1 1 1 1]


In [17]:
# whenever slicing is used no extra memory is allocated
print(arr)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]


In [18]:
# copy() -> create new numpy memory for array

arr3 = arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]


In [19]:
arr[:] = 0

In [20]:
print(arr)
print(arr3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148]
