In [1]:
import numpy as np

In [2]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(arr2d[1][2])
print(arr2d[0][0])
print(arr2d[1])

6
1
[4 5 6]


In [4]:
#slicing in 2d array

slice1 = arr2d[0:2,0:2]
print(slice1)

[[1 2]
 [4 5]]


In [5]:
slice2 = arr2d[0:2,0:3]
print(slice2)

[[1 2 3]
 [4 5 6]]


In [6]:
slice3 = arr2d[:2,:3]
print(slice3)

[[1 2 3]
 [4 5 6]]


In [7]:
slice4 = arr2d[1:,2:]
print(slice4)

[[6]
 [9]]


In [10]:
#loop to change indexes

arr_len = arr2d.shape
print(arr_len)

(3, 3)


In [12]:
row = arr_len[0]
col = arr_len[1]

for i in range(row):
    arr2d[i][0] = i
print(arr2d)

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [13]:
#access rows using list of index value

print(arr2d)
print(arr2d[[0,1]])
print(arr2d[[2,0]])

[[0 2 3]
 [1 5 6]
 [2 8 9]]
[[0 2 3]
 [1 5 6]]
[[2 8 9]
 [0 2 3]]
