In [1]:
import numpy as np

In [2]:
#creating 1D numpy array

mylist1 = [100,101,103]

myarray = np.array(mylist1)

print(myarray)

[100 101 103]


In [4]:
#'creating 2d np array

mylist2 = [200,201,202]

myarray2d = np.array([mylist1, mylist2])

print(myarray2d)

[[100 101 103]
 [200 201 202]]


In [5]:
# shape tell the dimention of the array

print(myarray2d.shape)

(2, 3)


In [6]:
# dtype tells the datatype

print(myarray.dtype)

int32


In [10]:
#array creation and initialization function zeroes

zero_array = np.zeros(5)
print(zero_array)

zero_array2d = np.zeros([5,3])
print(zero_array2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#array creation and initialization function ones

zero_array = np.ones(5)
print(zero_array)

zero_array2d = np.ones([5,3])
print(zero_array2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#empty array gives junks value

zero_array = np.empty(5)
print(zero_array)

zero_array2d = np.empty([5,3])
print(zero_array2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# eye - identity matrix

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#creating arrays in Arthematic Progression - arange

ap_array = np.arange(0,50,2)
print(ap_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
