In [1]:
import numpy as np

In [3]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
B = np.arange(0,90,5)
print(B)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]


In [5]:
C = np.arange(5,10)
print(C)

[5 6 7 8 9]


In [6]:
#square root of every element of A
D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [7]:
#exponential of elemenr of A
# e^x
E = np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [10]:
F = np.random.rand(5)
print(F)

F = np.random.rand(5,5)
print(F)

[0.70822923 0.6072452  0.6587704  0.2014793  0.52332028]
[[0.17073959 0.98121806 0.8889268  0.06571622 0.47240794]
 [0.16452778 0.11741931 0.03215227 0.58240071 0.00321456]
 [0.97701164 0.03778341 0.50585433 0.6850781  0.15652116]
 [0.15265163 0.59065563 0.18164283 0.01880736 0.48564105]
 [0.47754555 0.1284962  0.48535214 0.36335101 0.17035746]]


In [11]:
print(A)
print(D)
G = np.add(A,D)
print(G)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]
[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [13]:
A = np.array([1,5,7,10])
B = np.array([0,6,8,9])
H = np.maximum(A,B)
print(H)

[ 1  6  8 10]
