In [1]:
import numpy as np

In [2]:
#scalar operation are performed on each element of an array

In [3]:
#scalar multiplication

arr1 = np.array([[1,2,3],[5,6,7]])
print(arr1)

[[1 2 3]
 [5 6 7]]


In [4]:
arr2 = arr1 * arr1
print(arr2)

[[ 1  4  9]
 [25 36 49]]


In [6]:
#exponention operatin using **

arr3 = arr1**3
print(arr3)

[[  1   8  27]
 [125 216 343]]


In [7]:
# subtraction

arr4 = arr3 - arr2
print(arr4)

[[  0   4  18]
 [100 180 294]]


In [8]:
#scalar division 
arr5 = 1/arr1
print(arr5)

[[1.         0.5        0.33333333]
 [0.2        0.16666667 0.14285714]]
