In [19]:
import numpy as np

In [2]:
!pip install pandas

In [3]:
#What is Pandas
#what is series

In [4]:
#pandas -> high level data manupulation tool
#       -> built in numpy library
#       -> extends the functionality of numpy
#       -> provides two data structure(series and dataframe)

In [5]:
#what is series

In [6]:
#series is 1d labeled Array
#capable of holding data of any type
#series has indexes similar to numpy
#indexes can be numerical or char labels
#like 1 column of an exel sheet

In [23]:
import pandas as pd
from pandas import Series

In [12]:
#create a simple series variable
s1 = Series([5,10,15,20])
print(s1)

0     5
1    10
2    15
3    20
dtype: int64


In [13]:
print(s1.values)

[ 5 10 15 20]


In [15]:
print(s1.index)

RangeIndex(start=0, stop=4, step=1)


In [16]:
print(s1.index.values)

[0 1 2 3]


In [17]:
#create Series from numpy

In [20]:
revenue_arr = np.array([400,300,200,100])
print(revenue_arr)

[400 300 200 100]


In [25]:
revenue_series = pd.Series(revenue_arr)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int32


In [27]:
#create series with custom indexes

In [29]:
revenue = Series(revenue_arr, index=['uber','ola','cscw','wcwc'])
print(revenue)

uber    400
ola     300
cscw    200
wcwc    100
dtype: int32


In [30]:
revenue['ola']

300

In [31]:
print(revenue[revenue>250])

uber    400
ola     300
dtype: int32


In [32]:
print('ola' in revenue)

True


In [33]:
print('sdc' in revenue)

False


In [34]:
#to_dict()

In [35]:
revenue_dict = revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'cscw': 200, 'wcwc': 100}


In [36]:
#addition of two series

In [37]:
print(revenue)
print(revenue+revenue)

uber    400
ola     300
cscw    200
wcwc    100
dtype: int32
uber    800
ola     600
cscw    400
wcwc    200
dtype: int32


In [38]:
#assign name to series

In [39]:
revenue.name = "Company - Revenue"
revenue.index.name = "Company Name"

In [40]:
print(revenue)

Company Name
uber    400
ola     300
cscw    200
wcwc    100
Name: Company - Revenue, dtype: int32
